# todo: Delete this file after requirements.txt has been tested.
name: emcli
channels:
  - defaults
dependencies: # tested on WSL with Ubuntu 18.04
  # conda install pip
  # pip install numpy
  # pip install matplotlib
  # pip install tqdm
  # pip install cartopy
  # pip install xarray
  # pip install notebook
  # pip install netcdf4
  # pip install dask
  # pip install bottleneck
  # pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
  # pip install tqdm
  # pip install ipywidgets
  # python -m ipykernel install --user --name=emcli
  # pip install -e .


  - pytorch:pytorch
  - pytorch:torchvision
  - pytorch:cudatoolkit=11.3
  - python # =3.10.6
  - numpy # Tested with 1.19.2
  - pandas # 1.2.1
  - scikit-learn # 0.23.2
  - matplotlib # 3.3.2
  - tqdm # 4.55.1
  - jupyterlab # 3.2.4
  - scikit-image
  - pip
  - pip:
    - scikit-optimize # 0.8.1